name: PR merged

on:
  pull_request:
    types: [closed]

jobs:
  pr-merged:
    name: "PR merged"
    runs-on: ubuntu-latest
    steps: 
      - name: curl
        if: github.event.pull_request.merged == true
        run: curl --fail -X POST -u ${{ secrets.CI_BOT_USERNAME }}:${{ secrets.CI_BOT_PASSWORD }} '${{ secrets.CI_BOT_URL }}/github/pr/${{ github.event.pull_request.number }}/merged'
